:sparkles: Add inert drivers
libhal-google/libhal-soft pull request #23
Opened 2023-03-10 19:55 UTC by MaliaLabor

2023-03-11 00:25 UTC, kammce requested changes
Great work! Make the change as a new commit so we can keep track of it. We will squash it later.

2023-03-11 00:25 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_can.hpp
> +   * @param p_bus_on - State of inert can bus
This documentation is a bit confusing. You should make it clear the behavior of setting this value true or false.

2023-03-11 00:25 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_output_pin.hpp
> +   * @param p_level - level_t object to retrun when level() is called
Typo.
And it should be explained that this value can be changed based on calls to `level(bool)`

2023-03-11 00:25 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_i2c.hpp
> +    [[maybe_unused]] std::span<hal::byte> p_data_in,
p_data_in is an out parameter meaning that users will look at this buffer after the function is called. It would be good to have a default value for what should be returned/written into the buffer just like serial.

2023-03-11 00:25 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_spi.hpp
> +    [[maybe_unused]] std::span<hal::byte> p_data_in,
Same note as i2c.

2023-03-11 00:25 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_steady_clock.hpp
> +    return m_uptime;
It may be good to simply increment this value by one. That way this can be used in delay functions and other uses. Otherwise using it will deadlock the system.

2023-03-11 00:25 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_steady_clock.hpp
> +    return m_uptime;
That would make the factory function's uptime_t value the starting value.

2023-03-11 22:21 UTC, kammce requested changes

2023-03-11 22:21 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_serial.hpp
> +#pragma once
Can you remove the inert_serial and inert_can. We can add those back later on. But for now, we should remove them.

2023-03-12 21:36 UTC, MaliaLabor commented on include/libhal-soft/inert_drivers/inert_serial.hpp
> +#pragma once
Moved inert_can and inert_serial and their test files into incomplete_drivers folders

2023-03-12 21:48 UTC, kammce requested changes

2023-03-12 21:48 UTC, kammce commented on include/libhal-soft/inert_drivers/inert_socket.hpp
> +#pragma once
Lets remove socket as well. And anything that takes a `std::span<hal::byte>`

2023-03-12 21:56 UTC, MaliaLabor commented on include/libhal-soft/inert_drivers/inert_socket.hpp
> +#pragma once
moved socket, spi, and i2c to incomplete

2023-03-13 04:18 UTC, kammce approved these changes

2023-03-14 22:20 UTC, merged