:white_check_mark: Add unit tests to package build
libhal-google/libhal-soft pull request #9
Opened 2023-03-06 03:46 UTC by MaliaLabor

:bug: Updated return type for i2c_minimum_speed::transaction

2023-03-06 15:32 UTC, kammce requested changes
Can you update the CI so it runs correctly. Currently it still points to libhal/libhal when it should point to libhal/ci

2023-03-06 17:41 UTC, MaliaLabor commented
> Can you update the CI so it runs correctly. Currently it still points to libhal/libhal when it should point to libhal/ci

Done

2023-03-06 20:00 UTC, kammce requested changes

2023-03-06 20:00 UTC, kammce commented on include/libhal-soft/i2c_minimum_speed.hpp
> +      m_i2c->transaction(p_address, p_data_out, p_data_in, p_timeout));
Actually... this should be possible without `HAL_CHECK`.

2023-03-07 01:28 UTC, MaliaLabor commented on include/libhal-soft/i2c_minimum_speed.hpp
> +      m_i2c->transaction(p_address, p_data_out, p_data_in, p_timeout));
Ok, I changed it back

2023-03-07 16:35 UTC, kammce approved these changes

2023-03-09 00:18 UTC, merged